### ISSUE TITLE
Scroll to bottom covers horizontal scrollbar when present

### ISSUE THREAD

**Issue by bcorcoran** [spatie/nova-tail-tool#7]
If you have long lines in log output that cause horizontal scrolling, the scroll to bottom element will prevent you from using the mouse to scroll left and right, as the element fully covers the scrollbar when present. Once you are at the bottom of the output and the button goes away, the scroll bar of course works as it should.

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this.
